### ISSUE TITLE
Relationship with `ImageJ-Python-Bridge`?

### ISSUE THREAD

**Issue by jaimergp** [MontpellierRessourcesImagerie/napari-J#1]
Hello!

A part of the napari team is migrating the plugin ecosystem to conda-forge. We are reviewing this specific project [here](https://github.com/conda-forge/staged-recipes/pull/17914), where I stumbled upon the two packages being distributed in this repo:

* napari_j
* ijpb

It looks like the latter refers to another project in this organization, ImageJ-Python-Bridge, and I would like to clarify what's the status/relationship of both projects:

* Can people use them separately or are they tightly coupled?
* Are they developed at the same pace or do they have different release schedules?
* Will ImageJ-Python-Bridge be distributed on its own on PyPI at some point?
* In essence, should we package napari_j together with ijpb or not?

Thanks!

**Comment by volker-baecker** [comment]
Hi @jaimergp,
short answer, no they should not be packaged together.
ijpb provides a proxy that allows to send commands from ImageJ to an ipython kernel. The idea of napari_j is to combine napari and imagej by using jpype for one direction and ijpb for the other direction with ijpb connecting to the ipython kernel from which the jvm was started. 
- each package is or will be useful on its own
- our mission is to do image analysis for the users of the facility, any software we write is only a byproduct. So there are no release schedules and we work on a software only within the context of a given image analysis project for our users. 
- It will probably be distributed on its own, I'm not sure if pypi is the right place, since it is a jython.
- Do not distribute them together, ijpb is not currently used by napari_j. ijpb will probably be a prerequisite for napari_j later.
Best,
Volker

**Comment by jaimergp** [comment]
Thanks for the super clear explanation! I'll submit a patch to fix the accidental ijpb inclusion then, if that's ok!

**Comment by volker-baecker** [comment]
Ok, thank you.
